#!/usr/bin/env python3
import argparse
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "lib"))
from logger import get_logger


def parse_args():
    parser = argparse.ArgumentParser(
        prog="download",
        description="Download a file from the server.",
        formatter_class=lambda prog: argparse.HelpFormatter(
            prog,
            width=120,
            max_help_position=50,
        ),
    )

    verbosity = parser.add_mutually_exclusive_group()
    verbosity.add_argument(
        "-v", "--verbose", action="store_true", help="increase output verbosity"
    )
    verbosity.add_argument(
        "-q", "--quiet", action="store_true", help="decrease output verbosity"
    )

    parser.add_argument(
        "-H",
        "--host",
        type=str,
        default="127.0.0.1",
        metavar="<addr>",
        help="server IP address",
    )
    parser.add_argument(
        "-p", "--port", type=int, default=8080, metavar="<port>", help="server port"
    )
    parser.add_argument(
        "-d",
        "--dst",
        type=str,
        required=True,
        metavar="<filepath>",
        help="destination file path",
    )
    parser.add_argument(
        "-n",
        "--name",
        type=str,
        required=True,
        metavar="<filename>",
        help="file name",
    )
    parser.add_argument(
        "-r",
        "--protocol",
        type=str,
        choices=["saw", "gbn"],
        default="saw",
        metavar="<protocol>",
        help="error recovery protocol: saw (Stop & Wait) or gbn (Go-Back-N)",
    )

    return parser.parse_args()


def main():
    args = parse_args()
    logger = get_logger("download", args.verbose, args.quiet)

    logger.debug(f"Host: {args.host}, Port: {args.port}")
    logger.debug(f"Destination: {args.dst}, Name: {args.name}")
    logger.debug(f"Protocol: {args.protocol}")
    logger.info(f'Starting download of "{args.name}" -> "{args.dst}"')

    # TODO: implementar lógica de download


if __name__ == "__main__":
    main()
