#!/usr/bin/env python3
import sys
import os
import argparse
import threading
import socket

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "lib"))

from logger import get_logger
import stop_and_wait as sw
import go_back_n as gbn

from protocol import (
    parse_packet,
    parse_upload_req,
    parse_download_req,
    build_error,
    build_ack_with_port,
    build_ack_with_port_and_size,
)

from constants import (
    MSG_UPLOAD_REQ,
    MSG_DOWNLOAD_REQ,
    PROTOCOL_GBN,
    MAX_PACKET_SIZE,
)


def get_transfer_funcs(proto: int):
    if proto == PROTOCOL_GBN:
        return gbn.send, gbn.receive
    return sw.send, sw.receive


def parse_args():
    parser = argparse.ArgumentParser(
        prog="start-server",
        description="Start the file transfer server.",
        formatter_class=lambda prog: argparse.HelpFormatter(
            prog,
            width=120,
            max_help_position=50,
        ),
    )

    verbosity = parser.add_mutually_exclusive_group()
    verbosity.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="increase output verbosity",
    )
    verbosity.add_argument(
        "-q", "--quiet", action="store_true", help="decrease output verbosity"
    )

    parser.add_argument(
        "-H",
        "--host",
        type=str,
        default="0.0.0.0",
        metavar="<addr>",
        help="service IP address",
    )
    parser.add_argument(
        "-p",
        "--port",
        type=int,
        default=8080,
        metavar="<port>",
        help="service port",
    )
    parser.add_argument(
        "-s",
        "--storage",
        type=str,
        default="./storage",
        metavar="<path>",
        help="storage dir path",
    )

    return parser.parse_args()


def handle_upload(
    client_addr,
    filename,
    filesize,
    storage_dir,
    logger,
    protocol,
    lock,
    active_uploads,
    key,
):

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    """
    El sistema operativo asigna automáticamente un puerto
    con sock.bind(("0.0.0.0", 0)),
    este puerto se recupera mediante sock.getsockname() para
    luego mandarselo al cliente
    """
    sock.bind(("0.0.0.0", 0))
    _, client_port = sock.getsockname()

    with lock:
        active_uploads[key] = client_port

    sock.sendto(build_ack_with_port(0, client_port), client_addr)
    logger.info(
        f'Recibiendo "{filename}" ({filesize} bytes) '
        f"en puerto {client_port} [{protocol=}]"
    )

    try:
        _, transfer_receive = get_transfer_funcs(protocol)

        filepath = os.path.join(storage_dir, filename)
        transfer_receive(sock, filepath, filesize, first_seq=1, logger=logger)

        logger.info(f'Upload "{filename} completado')

    except Exception as e:
        logger.error(f'Error en upload de "{filename}": {e}')

    finally:
        with lock:
            active_uploads.pop(key, None)
        sock.close()


def handle_download(
    client_addr,
    filename,
    storage_dir,
    logger,
    proto,
    lock,
    active_downloads,
    key,
):
    transfer_send, _ = get_transfer_funcs(proto)

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(("0.0.0.0", 0))
    _, client_port = sock.getsockname()

    filepath = os.path.join(storage_dir, filename)

    if not os.path.exists(filepath):
        logger.error(f'Archivo no encontrado: "{filename}"')
        sock.sendto(build_error("archivo no encontrado"), client_addr)
        with lock:
            active_downloads.pop(key, None)
        sock.close()
        return

    filesize = os.path.getsize(filepath)

    with lock:
        active_downloads[key] = (client_port, filesize)

    sock.sendto(
        build_ack_with_port_and_size(0, client_port, filesize), client_addr
    )

    logger.info(
        f'Enviando "{filename}" ({filesize} bytes) '
        f"en puerto {client_port} [{proto=}]"
    )

    try:
        with open(filepath, "rb") as f:
            file_data = f.read()

        transfer_send(sock, client_addr, file_data, first_seq=1, logger=logger)

        logger.info(f'Download "{filename}" completado')

    except Exception as e:
        logger.error(f'Error en download de "{filename}": {e}')

    finally:
        with lock:
            active_downloads.pop(key, None)
        sock.close()


def main():
    args = parse_args()
    logger = get_logger("start-server", args.verbose, args.quiet)

    logger.debug(f"Host: {args.host}, Port: {args.port}")
    logger.debug(f"Storage dir: {args.storage}")
    logger.info(f"Server starting on {args.host}:{args.port}")
    logger.info(f"Storage directory: {args.storage}")

    os.makedirs(args.storage, exist_ok=True)

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind((args.host, args.port))

    active_uploads = {}
    active_downloads = {}
    lock = threading.Lock()

    while True:
        try:
            data, client_addr = sock.recvfrom(MAX_PACKET_SIZE)
        except Exception as e:
            logger.error(f"Error recibiendo paquete: {e}")
            continue

        try:
            packet = parse_packet(data)
        except Exception as e:
            logger.error(f"Paquete malformado de {client_addr}: {e}")
            sock.sendto(build_error("paquete malformado"), client_addr)
            continue

        if packet["type"] == MSG_UPLOAD_REQ:
            filename, filesize, protocol = parse_upload_req(packet["payload"])

            key = (client_addr, filename, filesize, protocol)

            with lock:
                if key in active_uploads:
                    transfer_port = active_uploads[key]
                    sock.sendto(
                        build_ack_with_port(0, transfer_port), client_addr
                    )

                    logger.debug(
                        f"UPLOAD duplicado de {client_addr}"
                        f"para '{filename}'"
                        f"reenviando puerto {transfer_port}"
                    )
                    continue

            clientThread = threading.Thread(
                target=handle_upload,
                args=(
                    client_addr,
                    filename,
                    filesize,
                    args.storage,
                    logger,
                    protocol,
                    lock,
                    active_uploads,
                    key,
                ),
                daemon=True,
            )

            clientThread.start()

        elif packet["type"] == MSG_DOWNLOAD_REQ:
            filename, protocol = parse_download_req(packet["payload"])

            key = (client_addr, filename, protocol)

            with lock:
                if key in active_downloads:
                    transfer_port, filesize = active_downloads[key]
                    sock.sendto(
                        build_ack_with_port_and_size(
                            0, transfer_port, filesize
                        ),
                        client_addr,
                    )
                    logger.debug(
                        f"DOWNLOAD duplicado de {client_addr}"
                        f"para '{filename}', "
                        f"reenviando puerto {transfer_port}"
                    )
                    continue

            clientThread = threading.Thread(
                target=handle_download,
                args=(
                    client_addr,
                    filename,
                    args.storage,
                    logger,
                    protocol,
                    lock,
                    active_downloads,
                    key,
                ),
                daemon=True,
            )
            clientThread.start()

        else:
            logger.error(
                f"Tipo de paquete no reconocido de {client_addr}:"
                f"{packet['type_name']}"
            )
            sock.sendto(
                build_error("tipo de paquete no reconocido"), client_addr
            )


if __name__ == "__main__":
    main()
